### ISSUE TITLE
improve regex expressions for mapping user commands

### ISSUE THREAD

**Issue by AhmetTanakol** [Rostlab/JS18_ProjectB_Group3#53]

**Comment by syxolk** [comment]
What needs to be done here? As a starter, you could just replace all the spaces in your regex by `\s+` (any number of whitespace).

**Comment by AhmetTanakol** [comment]
@syxolk yeah it makes sense.  I am working on a regex expression something like this `(?:[\s]|^)(title|"([^"]*)")(?=[\s]|$)` So this captures the word `title` and words between quotation marks (so we can understand which is the new value of title). I still need to figure out how to use it in our code.

**Comment by AhmetTanakol** [comment]
Please check the #61
